version: '3'

services:
  server:
    build: server/
    network_mode: host
    command: npm run start
    ports:
      - 8080:8080

  agent:
    build: agent/
    command: npm run start
    network_mode: host
    ports:
      - 8001:8001
    depends_on:
      - server
